#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Aug 22 21:17:45 -03 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 8db14257eccd483b919e25aa4c977429 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot ejer_1_tb_behav xil_defaultlib.ejer_1_tb -log elaborate.log"
xelab -wto 8db14257eccd483b919e25aa4c977429 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot ejer_1_tb_behav xil_defaultlib.ejer_1_tb -log elaborate.log

